// Matchmaking request/response contracts live in @footconnect/shared.
export {
  availabilityStatusSchema,
  buildCreateTeamAvailabilitySchema,
  challengeActionSchema,
  challengeStatusSchema,
  createMatchChallengeSchema,
  createTeamAvailabilitySchema,
  matchChallengeConditionsSchema,
  matchChallengeDetailSchema,
  matchChallengeResponseSchema,
  matchChallengeSummarySchema,
  opponentRecommendationSchema,
  overlappingWindowSchema,
  paginatedRecommendationsSchema,
  publicTeamAvailabilitySchema,
  recommendationExplanationSchema,
  recommendationsQuerySchema,
  recommendedTeamSummarySchema,
  respondToChallengeSchema,
  teamAvailabilitySchema,
  type AvailabilityStatus,
  type ChallengeAction,
  type ChallengeStatus,
  type CreateMatchChallengeInput,
  type CreateTeamAvailabilityInput,
  type CreateTeamAvailabilityPayload,
  type MatchChallengeConditions,
  type MatchChallengeDetail,
  type MatchChallengeResponse,
  type MatchChallengeSummary,
  type OpponentRecommendation,
  type OverlappingWindow,
  type PaginatedRecommendations,
  type PublicTeamAvailability,
  type RecommendationExplanation,
  type RecommendationsQuery,
  type RecommendedTeamSummary,
  type RespondToChallengeInput,
  type TeamAvailability,
} from "@footconnect/shared";
