// Matchmaking request/response contracts live in @footconnect/shared.
export {
  availabilityStatusSchema,
  buildCreateTeamAvailabilitySchema,
  createTeamAvailabilitySchema,
  opponentRecommendationSchema,
  overlappingWindowSchema,
  paginatedRecommendationsSchema,
  publicTeamAvailabilitySchema,
  recommendationExplanationSchema,
  recommendationsQuerySchema,
  recommendedTeamSummarySchema,
  teamAvailabilitySchema,
  type AvailabilityStatus,
  type CreateTeamAvailabilityInput,
  type CreateTeamAvailabilityPayload,
  type OpponentRecommendation,
  type OverlappingWindow,
  type PaginatedRecommendations,
  type PublicTeamAvailability,
  type RecommendationExplanation,
  type RecommendationsQuery,
  type RecommendedTeamSummary,
  type TeamAvailability,
} from "@footconnect/shared";
